# Generated by Django 4.0.2 on 2024-08-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=64)),
                ('front', models.CharField(max_length=1024)),
                ('back', models.CharField(max_length=1024)),
            ],
        ),
    ]
